//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        public int DebtId { get; set; }
        public Nullable<decimal> DebtAmount { get; set; }
        public Nullable<int> DebtMaturity { get; set; }
        public string DebtSituation { get; set; }
        public Nullable<int> CostumerId { get; set; }
        public Nullable<int> PaymentId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
